### ISSUE TITLE
Crash when dragging a block.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly-android#257]
I think this looks like a known RecyclerView bug, but could also be a reference from the toolbox that wasn't cleared, or was cleared too early.

```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
    at android.view.ViewGroup.addViewInner(ViewGroup.java:4309)
    at android.view.ViewGroup.addView(ViewGroup.java:4145)
    at android.view.ViewGroup.addView(ViewGroup.java:4117)
    at com.google.blockly.android.ui.BlockListView$Adapter.onBindViewHolder(BlockListView.java:268)
    at com.google.blockly.android.ui.BlockListView$Adapter.onBindViewHolder(BlockListView.java:247)
    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5504)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4741)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
    at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2625)
```

Not sure how to trigger it.

**Comment by AnmAtAnm** [comment]
Have not seen this bug.  Deprioritizing.

**Comment by AnmAtAnm** [comment]
Closing for lack of reports. Reopen if reproduced.
