### ISSUE TITLE
Crash: trashedBlock not found in mDeletedBlocks

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly-android#265]
No repeatable sequence yet.  Occurred on a development branch.

```
java.lang.IllegalArgumentException: trashedBlock not found in mDeletedBlocks
    at com.google.blockly.model.Workspace.addBlockFromTrash(Workspace.java:138)
    at com.google.blockly.android.control.BlocklyController.addBlockFromTrash(BlocklyController.java:683)
    at com.google.blockly.android.TrashFragment$1.getDraggableBlockGroup(TrashFragment.java:71)
    at com.google.blockly.android.ui.BlockListView.getWorkspaceBlockGroupForTouch(BlockListView.java:206)
    at com.google.blockly.android.ui.BlockListView$DragHandler$1.run(BlockListView.java:219)
    at com.google.blockly.android.ui.Dragger$5.run(Dragger.java:490)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by AnmAtAnm** [comment]
Deprioritized. Have not seen since reported.

**Comment by AnmAtAnm** [comment]
Closing for lack of reports. Reopen if reproduced.
