### ISSUE TITLE
Crash while pinch zooming

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly-android#288]
FATAL EXCEPTION: main
                                                                         Process: com.google.blockly.demo, PID: 14736
                                                                         java.lang.IllegalArgumentException: pointerIndex out of range
                                                                             at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                             at android.view.MotionEvent.getX(MotionEvent.java:2057)
                                                                             at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
                                                                             at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:110)
                                                                             at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:462)
                                                                             at com.google.blockly.android.ui.VirtualWorkspaceView.onTouchEvent(VirtualWorkspaceView.java:200)
                                                                             at android.view.View.dispatchTouchEvent(View.java:9300)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                             at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                             at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                             at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                             at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                             at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                             at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                             at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                         	at android.view.ViewRootImpl$WindowInputEventR

**Comment by RoboErikG** [comment]
To reproduce do a bunch of random touches with 4-5 fingers at once, starting with a pinch-zoom.
