### ISSUE TITLE
Clear action does not move blocks to the trash

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly-android#34]
User should be able to retrieve old blocks, regardless of how they are deleted.

**Comment by adamlinscott** [comment]
Got the following error when running:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.google.blockly.demo, PID: 24858
                  java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.blockly.android.TrashFragment com.google.blockly.android.control.BlocklyController.getTrashFragment()' on a null object reference
                      at com.google.blockly.android.ui.CategoryTabs.onCategoryClicked(CategoryTabs.java:231)
                      at com.google.blockly.android.ui.CategoryTabs.access$200(CategoryTabs.java:51)
                      at com.google.blockly.android.ui.CategoryTabs$CategoryAdapter$1.onClick(CategoryTabs.java:309)
                      at android.view.View.performClick(View.java:5637)
                      at android.view.View$PerformClick.run(View.java:22429)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by ChrisA89** [comment]
This is quite old. Is it still something you want? The clear button current removes everything from the workspace and the trash. So would the expected behaviour of clear be to empty the trash, and then move the workspace into it?

**Comment by AnmAtAnm** [comment]
I think there are reasons to consider both options for different applications. It's probably a good idea to have both a `resetWorkspace()` and a `trashAllBlocks()` on the BlocklyController, making it relatively trivial for developers to choose either.  At the moment, my only preference for reseting is because it is already implemented and working.

**Comment by AnmAtAnm** [comment]
Fixed in #476.
