### ISSUE TITLE
Cannot create new AbstractBlocklyActivity

### ISSUE THREAD

**Issue by dropsy-unlp** [google/blockly-android#340]
Hi, i'm currently having an issue while following the steps detailed in: https://developers.google.com/blockly/guides/get-started/android

After doing everything the tutorial says I'm getting this exception:

`java.lang.NoClassDefFoundError: org.jacoco.agent.rt.internal_773e439.Offline
                                                       at com.google.blockly.android.AbstractBlocklyActivity.$jacocoInit(AbstractBlocklyActivity.java)
                                                       at com.google.blockly.android.AbstractBlocklyActivity.<init>(AbstractBlocklyActivity.java)
                                                       at com.fuentesfernandez.myapplication.MainActivity.<init>(MainActivity.java:16)
                                                       at java.lang.Class.newInstanceImpl(Native Method)
                                                       at java.lang.Class.newInstance(Class.java:1208)
                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2101)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                       at dalvik.system.NativeStart.main(Native Method)`

**Comment by RoboErikG** [comment]
Hi dropsy, were you able to solve this issue? We've had a couple reports of problems with Jacoco but haven't been able to reproduce yet.
