### ISSUE TITLE
Block drag fails on API 16

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly-android#537]
Tested on master.  😢 
```
620/com.google.blockly.demo E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.NullPointerException
     at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1153)
     at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1147)
     at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1147)
     at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1147)
     at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1147)
     at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1147)
     at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1147)
     at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1147)
     at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1147)
     at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1147)
     at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1147)
     at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1147)
     at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1147)
     at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1147)
     at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:3714)
     at android.view.ViewRootImpl.access$600(ViewRootImpl.java:97)
     at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:2955)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loop(Looper.java:137)
     at android.app.ActivityThread.main(ActivityThread.java:4745)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:511)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by AnmAtAnm** [comment]
Jorge reported a similar bug (same stack trace) on API 17 [here](https://groups.google.com/forum/#!topic/blockly/J034UOr-glw).

Steps:
1. Drag a block with a statement input into the workspace.
1. Drag another block, connecting to the statement input.

I've been able to duplicate this bug on both 16 and 17, but not 18 or 19. I have not be able to recreate the crash from the originally reported steps.

**Comment by AnmAtAnm** [comment]
If fixed and API 16 is supported again, consider reprioritizing #179.

**Comment by AnmAtAnm** [comment]
As of [June 5th dashboards](https://developer.android.com/about/dashboards/index.html), Jellybean 16 & 17 represent 7.5% of all Android users.
