### ISSUE TITLE
"Blockly Simple" crashed after updating

### ISSUE THREAD

**Issue by amalcao** [google/blockly-android#609]
If no default variables provided, the demo will crash when you click some category with variable shadow fields. 

The trackback info:

```
05-23 10:29:54.436 17404-17404/com.google.blockly.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.google.blockly.demo, PID: 17404
                                                                         java.lang.IllegalArgumentException: Expected variable name "null" not found.
                                                                             at com.google.blockly.android.ui.fieldview.BasicFieldVariableView$VariableViewAdapter.getIndexForVarName(BasicFieldVariableView.java:252)
                                                                             at com.google.blockly.android.ui.fieldview.BasicFieldVariableView$VariableViewAdapter.getOrCreateVariableIndex(BasicFieldVariableView.java:231)
                                                                             at com.google.blockly.android.ui.fieldview.BasicFieldVariableView$3.run(BasicFieldVariableView.java:174)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:158)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:7231)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
05-23 10:30:06.921 17404-17404/com.google.blockly.demo I/Process: Sending signal. PID: 17404 SIG: 9
```

**Comment by AnmAtAnm** [comment]
Sorry about this. This should now be fixed on both master and develop.
